model:
  initial_learning_rate: 0.00002
  batch_size: 1024
  epochs: 100
  patience: 20
  in_channels: 17
  out_channels: 128
  num_blocks: 64
  dropout_factor: 0.4
  num_workers: 4
  mlp_input: 1088
  mlp_output: 1
  mlp_hidden: 128

scheduler:
  patience: 2
  factor: 0.1

training:
  train_split: 0.8